#!/bin/bash
VERSION="1.2.3"

# Execute this script with 'bash -x SCRIPT' to activate debugging
if [ ${-/*x*/x} == 'x' ]; then
    PS4='+ ${BASH_SOURCE[0]}:${LINENO} ${FUNCNAME[0]}() |err=$?| \$ '
fi
set -e  # Fail on first error

SELF_NAME="$0"
SELF_NAME="${SELF_NAME#\.}"
SELF_NAME="${SELF_NAME##/*/}"
SELF_NAME="${SELF_NAME#/}"
SELF_NAME="${SELF_NAME%.sh}"
SELF_DIRNAME=$(cd "$(dirname $(type -p "$0"))" ; pwd)

# Includes
source "${SELF_DIRNAME}/colors.inc"
source "${SELF_DIRNAME}/header.inc"

function _version()
{
    echo "${SELF_NAME} v${VERSION}"
}

function _help()
{
    cat <<EOF
Execute a COMMAND in each FOLDERs.

Usage:
    ${SELF_NAME} FOLDER [FOLDER ...] -- COMMAND


OPTIONS:
    -v, --version   Display version.
    -h, --help      Display this help.
    -p, --parallel  Use of GNU parallel

    --              Mandatory. Separates the FOLDERs from the COMMAND.

EXAMPLES:
    ${SELF_NAME} repo*/ -- git status \| grep -E \'^On branch\'
    ${SELF_NAME} repo*/ -- 'git fetch --all --tags ; git pull'
    ${SELF_NAME} -p repo*/ -- 'git status | grep -E "^On branch"'
    ${SELF_NAME} -p repo*/ -- git fetch --all --tags \; git pull
EOF
}

function _main()
{
    FOLDERS=()
    local folder_sep_found=0

    args=$(getopt --options hvp --longoptions help,version,parallel --name "${SELF_NAME}" -- "$@")
    if [ $? -ne 0 ]; then
        >&2 echo_color "Error: Invalid options" $COLOR_RED
        exit 2
    fi

    USE_PARALLEL=0
    while [ $# -gt 0 ]; do
        case "$1" in
        -v|--version)
            _version
            exit 0
        ;;
        -h|--help)
            _help
            exit 0
        ;;
        -p|--parallel)
            USE_PARALLEL=1
            shift
        ;;
        --)
            folder_sep_found=1
            shift
            break
        ;;
        *)
            FOLDERS+=("$1")
            shift
        ;;
        esac
    done

    COMMAND=( "$@" )
    # declare -p FOLDERS # DEBUG
    # declare -p COMMAND # DEBUG

    #
    # Manage mandatory options
    #
    # '--' should be used and at least one folder should be given.
    if [ $folder_sep_found -eq 0 ]; then
        >&2 echo_color "Error: You have to separate FOLDERs and COMMAND by using ' -- '" $COLOR_RED
        exit 2
    elif [ ${#FOLDERS[@]} -eq 0 ]; then
        >&2 echo_color "Error: You have to specify at least one FOLDER" $COLOR_RED
        exit 2
    fi

    #
    # Manage existence of given folders
    #
    local folder
    for folder in "${FOLDERS[@]}"; do
        if [ ! -e "${folder}" ]; then
            >&2 echo_color "Error: '${folder}' was not found" $COLOR_RED
            exit 2
        elif [ ! -d "${folder}" ]; then
            >&2 echo_color "Error: '${folder}' is not a folder" $COLOR_RED
            exit 2
        fi
    done

    #
    # Manage existence of external products
    #
    if [[ $USE_PARALLEL == 1 ]]; then
        which parallel >& /dev/null
        local errcode=$?
        if [[ $errcode != 0 ]]; then
            >&2 echo_color 'Error: Unable to reach GNU parallel.' $COLOR_RED
            >&2 echo_color '       Did you install it? Is it present in your PATH env variable?' $COLOR_RED
            exit 2
        fi
    fi

    execute_command
}

function execute_command()
{
    if [[ $USE_PARALLEL == 1 ]]; then
        _execute_command_using_parallel
    else
        _execute_command_simply
    fi
}

function _execute_command_simply()
{
    local sep_char='-'
    for (( i=0 ; $i < ${#FOLDERS[@]} ; i++ )); do
        local folder="${FOLDERS[$i]}"
        local header="[$((i+1))] ${folder}"

        >&2 echo ""
        # Display a nice delimiter line, beginning with the folder name.
        >&2 echo_color "$(_header_left "${header}" "${sep_char}")" $COLOR_CYAN

        (
            cd "${folder}"
            # "${COMMAND[@]}" # WORKS but no color, only 1 command, no piped commands
            bash -c "${COMMAND[*]}" # WORKS with color, with multiple commands, with piped commands, but be careful with commands containing whitespaces
        )
    done
}

function _execute_command_using_parallel()
{
    local sep_char='-'
    local padding="$(_header_get_padding "${sep_char}")"
    local columns=$(tput cols)
    parallel --keep-order "header='[{#}] {} '" \; echo '' \; echo -ne '\\e['$COLOR_CYAN'm' \; echo -n '"${header}"' \; printf '%*.*s' 0 '$(( '${columns}'-${#header} ))' "${padding}" \; echo -e '\\e['$STYLE_NORMAL'm' \; cd "{}" \; "${COMMAND[@]}" ::: "${FOLDERS[@]}"

    # To use a function declared in the shell session , parallel needs to source its env_parallel
    # first and to be called with env_parallel. This is working but the sourcing is taking ~1.5s,
    # which is long when you use the command very often.
    #
    # source `which env_parallel.bash` env_parallel --keep-order "header='[{#}] {}'" \; echo "" \;
    # echo_color -- '"$(_header_left "${header}")"' $COLOR_CYAN \; cd "{}" \; "${COMMAND[@]}" :::
    # "${FOLDERS[@]}"
}

_main "$@"
